package redshift

import (
	"context"
	"fmt"
	"strconv"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var (
	_ datasource.DataSource              = &userDataSource{}
	_ datasource.DataSourceWithConfigure = &userDataSource{}
)

func newUserDataSource() datasource.DataSource {
	return &userDataSource{}
}

type userDataSource struct {
	frameworkClient
}

type userDataSourceModel struct {
	ID              types.String `tfsdk:"id"`
	Name            types.String `tfsdk:"name"`
	ValidUntil      types.String `tfsdk:"valid_until"`
	CreateDatabase  types.Bool   `tfsdk:"create_database"`
	ConnectionLimit types.Int64  `tfsdk:"connection_limit"`
	SyslogAccess    types.String `tfsdk:"syslog_access"`
	Superuser       types.Bool   `tfsdk:"superuser"`
	SessionTimeout  types.Int64  `tfsdk:"session_timeout"`
}

func (d *userDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_user"
}

func (d *userDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: `
This data source can be used to fetch information about a specific database user. Users are authenticated when they login to Amazon Redshift. They can own databases and database objects (for example, tables) and can grant privileges on those objects to users, groups, and schemas to control who has access to which object. Users with CREATE DATABASE rights can create databases and grant privileges to those databases. Superusers have database ownership privileges for all databases.
`,
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:    true,
				Description: "The user ID.",
			},
			userNameAttr: schema.StringAttribute{
				Required:    true,
				Description: "The name of the user account. The user name can't be `PUBLIC`.",
				Validators: []validator.String{
					stringvalidator.NoneOfCaseInsensitive("public"),
				},
			},
			userValidUntilAttr: schema.StringAttribute{
				Computed:    true,
				Description: "Date and time after which the user's password is no longer valid. By default the password has no time limit.",
			},
			userCreateDBAttr: schema.BoolAttribute{
				Computed:    true,
				Description: "Indicates whether the user is allowed to create new databases.",
			},
			userConnLimitAttr: schema.Int64Attribute{
				Computed:    true,
				Description: "The maximum number of database connections the user is permitted to have open concurrently. The limit isn't enforced for superusers.",
			},
			userSyslogAccessAttr: schema.StringAttribute{
				Computed:    true,
				Description: "A clause that specifies the level of access that the user has to the Amazon Redshift system tables and views. If `RESTRICTED` (default) is specified, the user can see only the rows generated by that user in user-visible system tables and views. If `UNRESTRICTED` is specified, the user can see all rows in user-visible system tables and views, including rows generated by another user. `UNRESTRICTED` doesn't give a regular user access to superuser-visible tables. Only superusers can see superuser-visible tables.",
			},
			userSuperuserAttr: schema.BoolAttribute{
				Computed:    true,
				Description: `Indicates whether the user is a superuser with all database privileges.`,
			},
			userSessionTimeoutAttr: schema.Int64Attribute{
				Computed:    true,
				Description: "The maximum time in seconds that a session remains inactive or idle. The range is 60 seconds (one minute) to 1,728,000 seconds (20 days). If no session timeout is set for the user, the cluster setting applies.",
			},
		},
	}
}

func (d *userDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.configureDataSource(req, resp)
}

func (d *userDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var model userDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &model)...)
	if resp.Diagnostics.HasError() {
		return
	}

	db := d.connect(&resp.Diagnostics)
	if db == nil {
		return
	}

	var useSysID, userValidUntil, userConnLimit, userSyslogAccess, userSessionTimeout string
	var userSuperuser, userCreateDB bool

	columns := []string{
		"user_id",
		"createdb",
		"superuser",
		"syslog_access",
		`COALESCE(connection_limit::TEXT, 'UNLIMITED')`,
		"session_timeout",
	}

	values := []interface{}{
		&useSysID,
		&userCreateDB,
		&userSuperuser,
		&userSyslogAccess,
		&userConnLimit,
		&userSessionTimeout,
	}

	userSQL := fmt.Sprintf("SELECT %s FROM svv_user_info WHERE user_name = $1", strings.Join(columns, ","))
	if err := db.QueryRow(userSQL, model.Name.ValueString()).Scan(values...); err != nil {
		resp.Diagnostics.AddError("Unable to read the user", err.Error())
		return
	}

	if err := db.QueryRow("SELECT COALESCE(valuntil, 'infinity') FROM pg_user_info WHERE usesysid = $1", useSysID).Scan(&userValidUntil); err != nil {
		resp.Diagnostics.AddError("Unable to read the user", err.Error())
		return
	}

	userConnLimitNumber := -1
	if userConnLimit != "UNLIMITED" {
		parsed, err := strconv.Atoi(userConnLimit)
		if err != nil {
			resp.Diagnostics.AddError("Unable to read the user's connection limit", err.Error())
			return
		}
		userConnLimitNumber = parsed
	}

	userSessionTimeoutNumber, err := strconv.Atoi(userSessionTimeout)
	if err != nil {
		resp.Diagnostics.AddError("Unable to read the user's session timeout", err.Error())
		return
	}

	model.ID = types.StringValue(useSysID)
	model.CreateDatabase = types.BoolValue(userCreateDB)
	model.Superuser = types.BoolValue(userSuperuser)
	model.SyslogAccess = types.StringValue(userSyslogAccess)
	model.ConnectionLimit = types.Int64Value(int64(userConnLimitNumber))
	model.ValidUntil = types.StringValue(userValidUntil)
	model.SessionTimeout = types.Int64Value(int64(userSessionTimeoutNumber))

	resp.Diagnostics.Append(resp.State.Set(ctx, model)...)
}
